### ISSUE TITLE
Inline text interferes with editing in some cases

### ISSUE THREAD

**Issue by jyboudreau** [JinZihang/vscode-jiralens#1]
While editing text, in some cases the `Not committed yet` inline indicator interferes with editing.

In this video, i'm selecting a line, and hitting `delete` to bring the line to the current line:
https://github.com/JinZihang/vscode-jiralens/assets/62624/32dfd8e1-5e58-460f-a55b-b28ef9e50391

It took me a while to figure out that JiraLens was causing this.

**Comment by JinZihang** [comment]
Thanks for the feedback, I will look into this.

**Comment by JinZihang** [comment]
The next version 0.2.0, which includes the fix for this issue, will be released tomorrow.

**Comment by JinZihang** [comment]
JiraLens version 0.2.0 has been released.
